version: '3.3'
services:
  leo-bus:
    image: leo-bus:deploy
    hostname: leo-bus-deploy
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    build:
      context: ../..
      dockerfile: docker/deploy/Dockerfile
    volumes:
      - ~/.bash_aliases:/root/.bash_aliases:ro
      - ~/.bashrc:/root/.bashrc:ro
    tty: true
